In [11]:
import numpy as np
import torch

In [20]:
# x.shape() = 1, 1, 28, 28
x = torch.tensor([[0, 1], [2, 1]]).view(1, 2, 2)
x

tensor([[[0, 1],
         [2, 1]]])

In [17]:
# Sample <num iter> vectors from euclidean sphere surface
num_iter = 10
d = 4

u = np.random.randn(num_iter, d)
u /= np.linalg.norm(u, axis=1).reshape(-1, 1)
u

array([[-0.23674786, -0.76573701,  0.54133671,  0.25407053],
       [-0.11159454,  0.09787071,  0.44575591, -0.88276251],
       [ 0.48946426,  0.64876888, -0.26700372, -0.51791186],
       [ 0.29348641,  0.2733523 , -0.88123401,  0.25014169],
       [ 0.6959608 ,  0.29294264, -0.46980105, -0.45728564],
       [-0.16184914, -0.3081667 , -0.9327134 , -0.09425416],
       [ 0.01613805, -0.18597095, -0.91691576, -0.352732  ],
       [-0.29170344,  0.64374265, -0.50335144, -0.49713361],
       [-0.31338177,  0.40232801, -0.17519753,  0.84215786],
       [ 0.98413355, -0.09695122, -0.13965834,  0.05076587]])

In [ ]:
torch.tensor(u).view([num_iter] + list((1, 2, 2, 1))[1:])

In [26]:
x_panded = x.expand(num_iter, 1, 2, 2).view(num_iter, d)
x_panded + u

tensor([[-0.2367,  0.2343,  2.5413,  1.2541],
        [-0.1116,  1.0979,  2.4458,  0.1172],
        [ 0.4895,  1.6488,  1.7330,  0.4821],
        [ 0.2935,  1.2734,  1.1188,  1.2501],
        [ 0.6960,  1.2929,  1.5302,  0.5427],
        [-0.1618,  0.6918,  1.0673,  0.9057],
        [ 0.0161,  0.8140,  1.0831,  0.6473],
        [-0.2917,  1.6437,  1.4966,  0.5029],
        [-0.3134,  1.4023,  1.8248,  1.8422],
        [ 0.9841,  0.9030,  1.8603,  1.0508]], dtype=torch.float64)

In [30]:
torch.cat([x, x], axis=0)

tensor([[[0, 1],
         [2, 1]],

        [[0, 1],
         [2, 1]]])

In [31]:
np.prod(x.shape)

4